---
- name: create weave yaml directory
  become: yes
  file:
    path: /etc/weave/yaml/
    state: directory
    mode: 0755

- name: copy weave DaemonSet file
  become: yes
  copy:
    src: weave-daemonset-k8s-v1.9.5.yaml
    dest: "/etc/weave/yaml/weave-daemonset-k8s.yaml"

- name: start weave DaemonSet
  command: >
    kubectl apply -f
    /etc/weave/yaml/weave-daemonset-k8s.yaml

# Ready count could not be done with jsonpath and filter because of issue
# https://github.com/kubernetes/kubernetes/issues/45546
- name: "get desired weave pod count"
  shell: >
    kubectl get ds --all-namespaces
    | grep weave-net
    | awk '{print $3;}'
  register: get_desired_count_weave

- name: wait for weave DaemonSet to be Ready
  shell: >
    kubectl get ds --all-namespaces
    | grep weave-net
    | awk '{print $5;}'
  register: get_ready_count_weave
  until: "{{get_desired_count_weave.stdout | int}} == {{get_ready_count_weave.stdout | int}}"
  # Wait for 6 minutes
  retries: 120
  delay: 3

# wait for kube-dns containers are ready
- name: "get kube-dns pod name"
  shell: >
    kubectl get pods --namespace=kube-system |
    grep kube-dns- |
    awk '{print $1;}' |
    tr -d '\n'
  register: get_pod_name

- name: "get kube-dns ready statuses"
  command: >
    kubectl get pods --namespace=kube-system {{get_pod_name.stdout}}
    -o jsonpath='{.status.containerStatuses[*].ready}'
  register: get_ready_statuses
  until: (get_ready_statuses.stdout | match('^(true\s)*true$'))
  retries: 120
  delay: 3
