---
- name: "wait for server to respond on ssh port"
  local_action: wait_for
    host={{ ansible_ssh_host | default(inventory_hostname) }}
    port={{ ansible_port | default(22) }}
    search_regex=OpenSSH
    delay=0
    connect_timeout=1
    timeout=360

- name: "get cloud-init log"
  become: yes
  command: >
    cat /var/log/cloud-init-output.log
  register: cloud_init_log

- name: create cloud init log message
  set_fact:
    cloud_init_msg: "{% if cloud_init_log.stdout.find('Using Kubernetes version') != -1 %}'Kubernetes master has started initialization successfully'{% else %}'Problem with init of master? {{ cloud_init_log.stdout}}'{% endif %}"

- name: print master cloud init log message
  debug:
    msg: "{{ cloud_init_msg }}"

- block:

  - name: "wait for all nodes to join the master"
    shell: >
      kubectl get nodes
      -o jsonpath='{.items[*].status.conditions[-1:].type}' |
      grep -o 'Ready' | wc -l
    register: get_ready_nodes
    until: "{{get_ready_nodes.stdout | int}} == {{nodes_count | int}}"
    # Wait for 15 minutes
    retries: 180
    delay: 5

  rescue:

  - name: "get cloud-init log"
    become: yes
    command: >
      cat /var/log/cloud-init-output.log
    register: cloud_init_log

  - name: print master cloud init log
    debug:
      msg: "{{ cloud_init_log.stdout }}"

  - name: fail play
    fail:
      msg: "All nodes have not joined the master"


