language: python # (Ansible)

sudo: required

services:
  - docker

branches:
  except:
    - /^experimental\/.*$/
    - /^exp\/.*$/
    - /^development\/.*$/
    - /^dev\/.*$/
    - /^testing\/.*$/
    - /^test\/.*$/
    - /^doc\/.*$/
    - /^docs\/.*$/
    - /^documentation\/.*$/

env:
  global:
    - TERRAFORM_VERSION=0.10.7
    - ANSIBLE_LINT_VERSION=3.4.15
  matrix:
    - HOST_CLOUD=openstack
    - HOST_CLOUD=gce
    - HOST_CLOUD=aws
    - HOST_CLOUD=azure

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck # code review tool

before_install:

  # Install code review tools
  # Install Terraform
  - >
      travis_retry curl
      "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
      > /tmp/terraform.zip
  - sudo unzip /tmp/terraform.zip -d /usr/bin
  - sudo chmod +x /usr/bin/terraform
  # Install pip deps
  - sudo pip install --upgrade pip
  - sudo pip install ansible-lint=="${ANSIBLE_LINT_VERSION}"
  # Pull hadolint
  - docker pull lukasmartinelli/hadolint
  # Install shfmt
  - >
      travis_retry sudo curl
      "https://github.com/mvdan/sh/releases/download/v2.1.0/shfmt_v2.1.0_linux_amd64"
      > /usr/bin/shfmt
  - sudo chmod +x /usr/bin/shfmt

  # Check code quality
  # check Terraform
  - terraform fmt -check=true common/cloudflare
  - terraform fmt -check=true common/inventory
  - terraform fmt -check=true "$HOST_CLOUD"
  # check Ansible
  # skip ANSIBLE0006: avoid using curl
  # skip ANSIBLE0012: missing change_when on command/shell etc.
  - ansible-lint -x ANSIBLE0006,ANSIBLE0012 playbooks/*.yml
  # check Shell
  - shellcheck bootstrap/*
  - shellcheck bin/*
  - shfmt -i 2 -ci -w bootstrap/*
  - shfmt -i 2 -ci -w bin/*
  - git diff --exit-code
  # check Dockerfile
  - docker run --rm -i lukasmartinelli/hadolint hadolint --ignore DL3008 --ignore DL3015 --ignore DL3013 - < Dockerfile

# Build Docker image
install: docker build -t kubenow/provisioners:latest .

before_script:

  # Copy kn bin
  - sudo cp bin/kn /usr/bin/

  # Init test deployment
  - kn init ${HOST_CLOUD} test-deployment
  - cd test-deployment

  # Overwrite ssh-key for debug purposes
  - echo -e "$TRAVIS_SSH_KEY_PRIV" > ssh_key
  - echo -e "$TRAVIS_SSH_KEY_PUB" > ssh_key.pub

  # RENDER CONFIGURATION

  # Common
  - sed -i -e "s/your-cluster-prefix/kubenow-ci-${TRAVIS_BUILD_NUMBER}-${HOST_CLOUD}/g" terraform.tfvars
  # AWS
  - sed -i -e "s/your-acces-key-id/${AWS_ACCESS_KEY_ID}/g" terraform.tfvars
  - sed -i -e "s#your-secret-access-key#${AWS_SECRET_ACCESS_KEY}#g" terraform.tfvars
  - sed -i -e "s/eu-west-1/${AWS_DEFAULT_REGION}/g" terraform.tfvars
  # GCE
  - printf '%s\n' "$GCE_CREDENTIALS" > "./service-account.json"
  - sed -i -e "s/your_project_id/${GCE_PROJECT_ID}/g" terraform.tfvars
  # AZURE
  - sed -i -e "s/your-subscription_id/${AZURE_SUBSCRIPTION_ID}/g" terraform.tfvars
  - sed -i -e "s/your-client_id/${AZURE_CLIENT_ID}/g" terraform.tfvars
  - sed -i -e "s/your-client_secret/${AZURE_CLIENT_SECRET}/g" terraform.tfvars
  - sed -i -e "s/your-tenant_id/${AZURE_TENANT_ID}/g" terraform.tfvars
  # OS
  - sed -i -e "s/your-pool-name/${OS_POOL_NAME}/g" terraform.tfvars
  - sed -i -e "s/external-net-uuid/${OS_EXTERNAL_NET_UUID}/g" terraform.tfvars
  - sed -i -e "s/your-master-flavor/${OS_MASTER_FLAVOR}/g" terraform.tfvars
  - sed -i -e "s/your-node-flavor/${OS_NODE_FLAVOR}/g" terraform.tfvars
  - sed -i -e "s/your-edge-flavor/${OS_EDGE_FLAVOR}/g" terraform.tfvars
  - sed -i -e "s/your-glusternode-flavor/${OS_NODE_FLAVOR}/g" terraform.tfvars
  # Enable edges
  - sed -i -e "s/# edge/edge/g" terraform.tfvars
  # Enable glusternodes
  - sed -i -e "s/# glusternode/glusternode/g" terraform.tfvars
  # Cloudflare
  - sed -i -e "s/# use_cloudflare/use_cloudflare/g" terraform.tfvars
  - sed -i -e "s/# cloudflare_email = \"your-cloudflare-email\"/cloudflare_email = \"${CI_CLOUDFLARE_EMAIL}\"/g" terraform.tfvars
  - sed -i -e "s/# cloudflare_token = \"your-cloudflare-token\"/cloudflare_token = \"${CI_CLOUDFLARE_TOKEN}\"/g" terraform.tfvars
  - sed -i -e "s/# cloudflare_domain = \"your-domain-name\"/cloudflare_domain = \"${CI_CLOUDFLARE_DOMAIN}\"/g" terraform.tfvars
  - sed -i -e "s/# cloudflare_subdomain = \"your-subdomain-name\"/cloudflare_subdomain = \"kubenow-ci-${TRAVIS_BUILD_NUMBER}-${HOST_CLOUD}\"/g" terraform.tfvars


script:
  # Deploy
  - kn apply
  # Test
  - kn ansible-playbook /opt/KubeNow/playbooks/infra-test.yml
  - kn kubectl get nodes # try to list nodes
  - kn helm list # try to helm list
  - kn ssh master 'uname && exit' # ssh to master and execute commands
  - kn openstack --version # try to run an openstack command
  - kn az --version # try to run an azure cli command
  - kn gcloud --version # try to run an gcloud cli command


after_script:
  - export TERRAFORM_OPT="-force" && travis_retry kn destroy
  - travis_retry terraform destroy -force "$HOST_CLOUD" # in case there is some problem with kn

jobs:
  include:
    # Docker push stage
    - stage: Push container
      before_install: true
      install: true
      before_script: true
      after_script: true
      script:
        # Build and push Docker image (needs to be build again in this stage)
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - >
            if [ $TRAVIS_BRANCH == 'master' ]; then
              docker build -t kubenow/provisioners:master .
              docker push kubenow/provisioners:master
            elif [ ! -z $TRAVIS_TAG ]; then
              docker build -t kubenow/provisioners:$TRAVIS_TAG \
                -t kubenow/provisioners:latest .
              docker push kubenow/provisioners:$TRAVIS_TAG
              docker push kubenow/provisioners:latest
            fi

notifications:
  email: false
  slack:
    secure: >
      ed+rC8Oc4EdZfptHGX1Xr5sNc+wQTyjb4rjJT0P/U/NBStmik7dnUfAK9vk6XYVDrrPZxmAz6A
      cJmEaxY4kdG2HBLBPD0keRxKh2rN2ZbjCTWuGlAomMkmNDcyeVoQI95HcT0nYHzgoUCGn7lgZ7
      9vBUhBqbJXUWbvkz7J5qn8Kx7PXWvmjW4YLu9RhuIP7JtZLDLJt9dgyeHXDm1CW3tvPPplv9e8
      l1GOcF2DBqodwd8+U5BTCNXf1DdwdvlmzIaZemy3sAsvNEr5wEIuO0Zw2cayhV80nf9fWW58ne
      NBV2i8oeAuCL/M3EkEE/Z4aI/zxBVRyTaeK0s+XKehlC7IDJxnMirbNn2X4yyUeWY/81DX+Hhb
      pip46TGQpS0sST8rBd7JYj0LjGSXj585xOcP67s9HdncnkVRdIdTOFX63m2bSE5tddJuOPggHZ
      VKM8k+twXsWpW7sCr95wnwlD/ARuuG3OTtV0HfnHpqvKLdBgJ1fEsmKXn6eAaDvcCQ0K5LUBUs
      yaZ9HHU7LYv7S760XgrmUEMR1SBsb9grFzANkAyhzApWQJ7wQbGD1IFX1kJl2v1Ii4WRgdVNll
      YcMeflpHWPYI0U0IVXYPPLuV5DOEoKfWsJpX3HtZswYLdNzrZkSB9DQ/LxkSAZZcbkj9GLCv2E
      igZHjgC3Ey2wwGIYQ=
