language: python # (Ansible)

sudo: required

branches:
  except:
    - /^experimental\/.*$/
    - /^exp\/.*$/
    - /^development\/.*$/
    - /^dev\/.*$/
    - /^testing\/.*$/
    - /^test\/.*$/
    - /^doc\/.*$/
    - /^docs\/.*$/
    - /^documentation\/.*$/

env:
  global:
    - PYBIN=/home/travis/virtualenv/python2.7.12/bin/python2.7
    - TERRAFORM_VERSION=0.7.8
    - ANSIBLE_VERSION=2.2.0.0
    - IMAGE_VERSION=v020
    - AWS_AMI_ID=ami-30251456
  matrix:
    - HOST_CLOUD=openstack
    - HOST_CLOUD=gce
    - HOST_CLOUD=aws

git:
  submodules: false

before_install:

  # Decrypt secrets
  - >
    openssl aes-256-cbc
    -K $encrypted_92d825aa39d7_key
    -iv $encrypted_92d825aa39d7_iv
    -in test/secret.enc
    -out test/secret.tgz
    -d

  # Extract secrets
  - tar xzvf test/secret.tgz -C test

  # Add the keypair to the agent
  - eval "$(ssh-agent -s)"
  - ssh-add test/secret/kubenow-ci

  # Get secrets
  - git submodule update --init --recursive

install:

  # Install Terraform
  - >
      curl
      https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      > /tmp/terraform.zip
  - sudo unzip /tmp/terraform.zip -d /usr/bin
  - sudo chmod +x /usr/bin/terraform

  # Install Ansible and pip deps
  - sudo pip install --upgrade pip
  - >
      sudo pip install
      ansible==${ANSIBLE_VERSION}
      j2cli

before_script:

  # Source test environment
  - source test/secrets-kubenow/host_cloud/CityCloud.sh
  - source test/secrets-kubenow/host_cloud/aws.sh

  # Render Terraform configuration
  - >
      env | j2 --format=env test/secrets-kubenow/tfvars/"$HOST_CLOUD".tfvars.j2 >
      ./terraform.tfvars

  # Render Cloudflare configuration
  - >
      env | j2 --format=env test/secrets-kubenow/cloudflare/conf.yml.j2 >
      playbooks/roles/cloudflare/vars/conf.yml

script:
  # AWS doesn't need image import
  - >
      if [ $HOST_CLOUD = 'openstack' ] || [ $HOST_CLOUD = 'gce' ]; then
        ansible-playbook \
        -i localhost \
        -e ansible_python_interpreter=$PYBIN \
        -e "credentials_file_path=$PWD/test/secrets-kubenow/host_cloud/gce-key.json" \
        playbooks/import-"$HOST_CLOUD"-image.yml
      fi
  - terraform get $HOST_CLOUD
  - terraform apply $HOST_CLOUD
  - ansible-playbook playbooks/install-core.yml
  - ansible-playbook playbooks/infra-test.yml

after_script:
  - terraform destroy -force $HOST_CLOUD
  - ansible-playbook playbooks/clean-cloudflare.yml
