language: python # (Ansible)

sudo: required

branches:
  except:
    - /^experimental\/.*$/
    - /^exp\/.*$/
    - /^development\/.*$/
    - /^dev\/.*$/
    - /^testing\/.*$/
    - /^test\/.*$/

before_install:
  # Install deps by HashiCorp
  - >
      curl
      https://releases.hashicorp.com/packer/0.11.0/packer_0.11.0_linux_amd64.zip
      > /tmp/packer.zip
  - >
      curl
      https://releases.hashicorp.com/terraform/0.7.8/terraform_0.7.8_linux_amd64.zip
      > /tmp/terraform.zip
  - sudo unzip /tmp/packer.zip -d /usr/bin
  - sudo unzip /tmp/terraform.zip -d /usr/bin
  - sudo chmod +x /usr/bin/packer
  - sudo chmod +x /usr/bin/terraform
  # Install Ansible
  - sudo pip install --upgrade pip
  - sudo pip install ansible==2.2.0.0
  # Add credentials for CI user
  - >
    echo -e "machine github.com\n  login mcapuccini-ci\n  password $GIT_PASS"
    >> ~/.netrc

install:
  - source test/secrets-kubenow/host_cloud/CityCloud.sh

script:
  - ansible-playbook -e "host_cloud=openstack" test/cheese-deployment.yml

env:
  global:
    - secure: "bvkgxAw4aAZzycX2grCtbMaMc05d7jIEafyxRFKk+RxR3NCL0UIldJQsybcdWpsaXbGeV63+FzOFaFmTb7DMrlIfkD/LGgAQY0mBX7HZubePeguzXk+qthUzo2pcTZw8je/Z7MM2sJx6Za88nc/90/f3QwGF1YMJa1D58wdFfImiiYuMCbHQ0FW7uPRIy57YyGQIyhkl+pOVpejcWeU0dVzk6Hv6PHJ2KxDikXw6cxhyuIZiiHmBsPwmAG9uItIfuUC41m/JwHSn1Uhu9D/FjUlEJxD+ajvGlqXyECphxlIscjZYd3bJRKGO7v17kRGGXaXQvZQ1gpZ+nxa8hBhkmQanTMaa95yKMMBRpsCnRRtxk6ed4q4y/45UG/1B2oSfX7FwII7clN5DGklxhlRCs4N090WgBWJLCkpqF4X5hmt1JXyIXjIUfV7AA1LsXIE1YT19RSYrQge/6gI86p81luvgH8zEjU6MrEniDEILkoiZR4E885TEh5xlkCyG8W10vj/FbpSUcsd6aA/AqWHosBa66OEbh46y5oFYbekW5xNL35FWjDnS7G1AhncIOp2HMJgT6xv6qfv0+SQ5Fv+oZV+VE7e5Rm//CrKDvpHWUFpi5bZNVdxhc4MxNqd1/2nCcwrNxZvn9XAbEbjbF/cjsCzNitpTLTcPRpa69y2HYZg="
