- hosts: master
  gather_facts: False
  roles:
    - hostnames
    - weave-network

- hosts: all
  gather_facts: False
  roles:
    - traefik

- hosts: edge
  gather_facts: False
  roles:
    - cloudflare
    
- hosts: master
  gather_facts: False
  roles:
    - helm
