################################################################
# Defaults
################################################################
defaultEntryPoints = ["http","https"]
################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"
################################################################
# ACME
################################################################
#[entryPoints]
#  [entryPoints.http]
#  address = ":80"
#    [entryPoints.http.redirect]
#    entryPoint = "https"
#  [entryPoints.https]
#  address = ":443"
#    [entryPoints.https.tls]
# Enable ACME (Let's Encrypt): automatic SSL
#[acme]
#email = ""
#storageFile = "/etc/traefik/acme/acme.json"
#entryPoint = "https"
#onDemand = true
#OnHostRule = true
