---
- name: load vars
  local_action: include_vars conf.yml

- name: set wildcard record
  local_action: set_fact
  args:
    cf_record: "*"
  when:
    - cf_subdomain is undefined

- name: set wildcard record (with subdomain)
  local_action: set_fact
  args:
    cf_record: "*.{{cf_subdomain}}"
  when:
    - cf_subdomain is defined

- name: call cloudlare API
  local_action: cloudflare_dns
  args:
    zone: "{{ cf_zone }}"
    record: "{{ cf_record }}"
    type: A
    value: "{{ ansible_ssh_host }}"
    state: "{{ cf_state | default('present') }}"
    account_email: "{{ cf_mail }}"
    account_api_token: "{{ cf_token }}"
