---
- hosts: master
  gather_facts: False
  tasks:
    - name: make sure all required pods are up and running
      command: >
        kubectl get pods --all-namespaces
      register: kubectl
      until: (kubectl.stdout.find('ContainerCreating') == -1) and (kubectl.stdout.find('SomethingElse') == -1)
      retries: 60
      delay: 3

    - name: add galaxy repo
      sudo: yes
      command: >
        helm repo add galaxy-helm-repo 
        https://pcm32.github.io/galaxy-helm-charts
      
    - name: install galaxy
      sudo: yes
      command: >
        helm install 
        --set use_ingress="yes",domain="{{ domain }}",external_ingress_controller="yes"
        galaxy-helm-repo/galaxy-simple
      
  


