- name: "get edge labels from inventory group"
  command: >
    kubectl get nodes {{ groups['edge'] | join(' ') }}
    -o jsonpath='{@..metadata.labels.role}'
  register: get_edge_roles
  when: edge_names is undefined

- name: "get edge labels from inventory variable"
  command: >
    kubectl get nodes {{ edge_names }}
    -o jsonpath='{@..metadata.labels.role}'
  register: get_edge_roles
  when: edge_names is defined

- name: "get roles from stdout"
  set_fact:
    edge_roles: get_edge_roles.stdout

- name: "print roles"
  debug: var=edge_roles

- name: "test edge labels"
  fail:
    msg: "unexpected edge lables: {{get_edge_roles.stdout}}"
  when: not (get_edge_roles.stdout | match('^(edge\s)*edge$'))
