---
- include: ../traefik-lb/main.yml

- hosts: master
  gather_facts: False
  tasks:
    - name: copy cheese-deployment.yml to master
      template:
        src: cheese-deployment.yml.j2
        dest: /home/ubuntu/cheese-deployment.yml
    - name: create cheese-deployment
      command: >
        kubectl apply -f /home/ubuntu/cheese-deployment.yml
