---
- hosts: edge
  tasks:
  - name: set record name
    set_fact:
      cf_record: "*"
    when: cf_subdomain is undefined
  - name: set record name (with subdomain)
    set_fact:
      cf_record: "*.{{cf_subdomain}}"
    when: cf_subdomain is defined
  - name: add wildcard record
    cloudflare_dns:
      zone: "{{ cf_zone }}"
      record: "{{ cf_record }}"
      type: A
      value: "{{ ansible_ssh_host }}"
      state: present
      account_email: "{{ cf_mail }}"
      account_api_token: "{{ cf_token }}"

- hosts: master
  tasks:
  - name: set record name
    set_fact:
      cf_record: "master"
    when: cf_subdomain is undefined
  - name: set record name (with subdomain)
    set_fact:
      cf_record: "master.{{cf_subdomain}}"
    when: cf_subdomain is defined
  - name: add master record
    cloudflare_dns:
      zone: "{{ cf_zone }}"
      record: "{{ cf_record }}"
      type: A
      value: "{{ ansible_ssh_host }}"
      state: present
      account_email: "{{ cf_mail }}"
      account_api_token: "{{ cf_token }}"
