- hosts: localhost
  gather_facts: False
  vars:
    img_version: "v020"
    timeout: 1800
  tasks:
    - name: "ensure shade is installed"
      pip:
        name: shade
    - name: "ensure urllib3 is updated"
      pip:
        name: urllib3
        version: 1.21
    - name: "set image facts"
      set_fact:
        image_name: "kubenow-{{img_version}}"
    - name: "download KubeNow image"
      get_url:
        url: "https://httpd.pharmb.io/kubenow-img/{{ image_name }}.qcow2"
        dest: /tmp/{{ image_name }}.qcow2
      notify:
        - delete local image
      async: "{{timeout}}"
      poll: 0
      register: kubenow_download
    - name: "wait for image download to be done"
      async_status: jid={{ kubenow_download.ansible_job_id }}
      register: download_status
      until: download_status.finished
      retries: "{{((timeout | int) / 60) | int}}"
      delay: 60
    - name: "upload image to OpenStack"
      os_image:
        name: "{{ image_name }}"
        filename: "/tmp/{{ image_name }}.qcow2"
        container_format: bare
        disk_format: qcow2
        state: present
        timeout: "{{timeout}}"
      async: "{{timeout}}"
      poll: 0
      register: kubenow_upload
    - name: "wait for image upload to be done"
      async_status: jid={{ kubenow_upload.ansible_job_id }}
      register: upload_status
      until: upload_status.finished
      retries: "{{((timeout | int) / 60) | int}}"
      delay: 60
  handlers:
    - name: delete local image
      file:
        path: "/tmp/{{ image_name }}.qcow2"
        state: absent
