# requires shade
- hosts: localhost
  gather_facts: False
  vars:
    img_version: "v020"
    timeout: 1800
  tasks:
    - name: "set image facts"
      set_fact:
        image_name: "kubenow-{{img_version}}"
    - name: "download KubeNow image"
      get_url:
        url: "https://httpd.pharmb.io/kubenow-img/{{ image_name }}.qcow2"
        dest: /tmp/{{ image_name }}.qcow2
      notify:
        - delete local image
    - name: "upload image to OpenStack"
      os_image:
        name: "{{ image_name }}"
        filename: "/tmp/{{ image_name }}.qcow2"
        container_format: bare
        disk_format: qcow2
        state: present
        timeout: "{{timeout}}"
  handlers:
    - name: delete local image
      file:
        path: "/tmp/{{ image_name }}.qcow2"
        state: absent
