- hosts: master
  gather_facts: False
  roles:
    - { role: common, tags: [ 'minimal' ] }
    - { role: weave-network, tags: [ 'minimal' ] }
    - { role: start-helm, tags: [ 'minimal' ] }
    - { role: traefik, tags: [ 'traefik' ] }
    - { role: heketi-gluster, tags: [ 'heketi-glusterfs' ], when glusternode_count is defined and glusternode_count > 0 }
