- hosts: master
  gather_facts: False
  roles:
    - { role: common, tags: [ 'minimal' ] }
    - { role: flannel-network, tags: [ 'minimal' ] }
    - { role: wait-kube-dns, tags: [ 'minimal' ] }
    - { role: start-helm, tags: [ 'minimal' ] }
    - { role: traefik, tags: [ 'traefik' ] }
    - { role: heketi-gluster, tags: [ 'heketi-glusterfs' ] }
