- hosts: master
  gather_facts: False
  roles:
    - { role: common, tags: [ 'minimal' ] }
    - { role: weave-network, tags: [ 'minimal' ] }
    - { role: start-helm, tags: [ 'minimal' ] }
    - { role: traefik, tags: [ 'traefik' ] }
    - { role: heketi, tags: [ 'heketi-glusterfs' ] }
    - { role: heketi-gluster-server, tags: [ 'heketi-glusterfs' ] }
    - { role: heketi-storage, tags: [ 'heketi-glusterfs' ] }
