- hosts: master
  gather_facts: False
  roles:
    - common
    - weave-network
    - start-helm
    - gluster-server
    - shared-volume

- hosts: all
  gather_facts: False
  roles:
    - traefik

- hosts: edge
  gather_facts: False
  roles:
    - cloudflare
